*** Settings ***
Resource        ../uitils/Settings.resource

*** Variables ***

${Elemento_Button_Cadastro}             id=Cadastros
${Elemento_Messege_QACodersAcademy}    class=css-g1743a
${Elemento_Button_Diretorias}          id=Diretorias
${Elemeto_Button_NovoCadastroDiretorias}   id=Novo Cadastro
${Elemento_Input_NomeDiretoria}            id=boardName
${Elemento_Button_SalvarDiretorias}        id=save 