name: ROBOT WEB 

on: push

job:
  Test: 
     run-on: windows-latest

      steps:
      - name: Checkout Repository
      # run: echo Fazendo checkout do repositorio
      uses: actions/checkout@v4

      - name: Set up Python
      # run: echo Instalação da versão 3.12 do Python
      uses: actions/setup-python@v5
      with:
      python-version: '3.12'

      - name: Install dependencies
      # run: echo Instalação das depedências do Projeto
      run: |
        echo Instalação das depedências do Projeto
        pip install robotframework
        pip install robotframework-seleniumlibrary      

      - name: Run Robot Framework tests
      # run: echo Executando os testes de API do Robot
      run: |
        echo Executando os testes de API do Robot
        robot --name "API and Web Tests" --outputdir results/ tests/web/
      - name: Test Report
      # run: echo Salvando o Report dos Testes
      uses: actions/upload-artifact@v4
      if: always()
      with:
      name: robot-framework-report-web
      path: result/



